---
title: "Untitled"
author: "Ruth Kristianingsih"
date: "28/01/2020"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("reports", stringr::str_remove(getwd(), here::here("scripts/r-scripts/")))) })
output:
  md_document:
    variant: markdown_github
---

# Results in training each-pathogen (with secreted non-effector data) datasets

```{r}
library(tidyverse)
```

## Fungi

### Training and Validation CNN-LSTM

```{r}
training_results_cnn_lstm <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_train_saved_cnn_lstm_fungi_secreted_data.csv")

training_results_cnn_lstm %>% 
  knitr::kable()
```


```{r}
val_results_cnn_lstm <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_val_saved_cnn_lstm_fungi_secreted_data.csv")

val_results_cnn_lstm %>% 
  knitr::kable()
```

### Training and Validation CNN-GRU

```{r}
training_results_cnn_gru <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_train_cnn_gru_fungi_secreted_data.csv")

training_results_cnn_gru %>% 
  knitr::kable()
```

```{r}
val_results_cnn_gru <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_val_cnn_gru_fungi_secreted_data.csv")

val_results_cnn_gru %>% 
  knitr::kable()
```



## Oomycete

### Training and Validation CNN-LSTM

```{r}
oomycete_training_results_cnn_lstm <- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted_single_training/df_results_train_saved_cnn_lstm_oomycete_secreted_data.csv") 

oomycete_training_results_cnn_lstm %>% 
  knitr::kable()
```


```{r}
oomycete_val_results_cnn_lstm <- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted_single_training/df_results_val_saved_cnn_lstm_oomycete.csv")

oomycete_val_results_cnn_lstm %>% 
  knitr::kable()
```


### Training and Validation CNN-GRU

```{r}
oomycete_training_results_cnn_gru <- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted/df_results_train_cnn_gru_saved_model1.csv")

oomycete_training_results_cnn_gru %>% 
  knitr::kable()
```


```{r}
oomycete_val_results_cnn_gru <- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted/df_results_val_cnn_gru_saved_model1.csv")

oomycete_val_results_cnn_gru %>% 
  knitr::kable()
```


## Fungi and Oomycete on test data for both CNN-LSTM and CNN-GRU

```{r}
cnn_lstm_test_fungi <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_test_saved_cnn_lstm_fungi_secreted_data.csv")
cnn_lstm_test_oomycete <- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted/df_results_test_saved_cnn_lstm_oomycete_secreted_data.csv")
cnn_gru_test_fungi <- data.table::fread("../../../../../data/secreted_data/training-results/fungi/results/secreted/df_results_test_cnn_gru_fungi_secreted_data.csv")
cnn_gru_test_oomycete<- data.table::fread("../../../../../data/secreted_data/training-results/oomycete/results/secreted/df_results_test_cnn_gru_saved_model1.csv")
```


```{r}
data.frame(model = c( "cnn_lstm_fungi", 
                         "cnn_gru_fungi", 
                         "cnn_lstm_oomycete", 
                         "cnn_gru_oomycete"), 
           accuracy = c(cnn_lstm_test_fungi %>% pull(acc), 
                        cnn_gru_test_fungi %>% pull(acc),
                        cnn_lstm_test_oomycete %>% pull(acc),
                        cnn_gru_test_oomycete %>% pull(acc))
) 
```



