---
title: "Untitled"
author: "Ruth Kristianingsih"
date: "17/01/2020"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("reports", stringr::str_remove(getwd(), here::here("scripts/r-scripts/")))) })
output:
  md_document:
    variant: markdown_github
---

# Getting secreted Organism name for fungi

## Load the libraries 

```{r}
library(tidyverse)

```

```{r}
# Loading the data

# Load the effector data obtained previously
effector_data <- data.table::fread("../../../data/getting-data-new/binary-class-data/effector_data.csv")

# Load phi base data
all_phi_base <- data.table::fread("../../../data/phi-base-current-data/phi-base_without_column_desc.csv")
```


```{r}
effector_data_class <- readRDS("../../../data/getting-data-new/multi-class-data/class_df_effectors.rds")
```



```{r}
effector_data <- effector_data %>% 
  dplyr::mutate(PathogenID = as.character(PathogenID))
```


```{r}
effector_data_complete <- effector_data %>% 
  left_join(effector_data_class %>% ungroup(), by ="PathogenID")
```

```{r}
list_protein_id <- effector_data_complete %>%
  pull(ProteinID)
```

```{r}
# Getting the information about the Gene names and Gene IDs, and the protein source
phi_base_prot <- all_phi_base %>%
  dplyr::filter(ProteinID %in% list_protein_id) %>%
  group_by(ProteinID, ProteinIDsource) %>%
  slice(1) %>%
  dplyr::select(ProteinIDsource, ProteinID, GeneIDsource, GeneID, Gene, PathogenID, Pathogenspecies, PathogenstrainID, Pathogenstrain)

# Getting the dictinct value of each data
phi_base_prot %>%
  dplyr::distinct(Gene) %>%
  nrow()
```

```{r}
# Change the class of pathogenID 

phi_base_prot <- phi_base_prot %>% 
  dplyr::mutate(PathogenID = as.character(PathogenID))
```


```{r}
effector_data_info <- phi_base_prot %>% 
  ungroup() %>% 
  left_join(effector_data_complete, by = "ProteinID") %>% 
  dplyr::select(c("ProteinID", "GeneID", "Gene", "PathogenID.x", "Pathogenspecies.x", "Pathogenstrain", "class")) %>%
  `colnames<-` (c("ProteinID", "GeneID", "Gene", "PathogenID", "Pathogenspecies", "Pathogenstrain", "class"))
```

## Fungi

```{r}
effector_data_info_fungi <- effector_data_info %>% 
  dplyr::filter(class == "fungi") 
```

```{r}
effector_data_info_fungi %>% 
  group_by(Pathogenspecies) %>% 
  summarise(count = n()) %>% 
  write.csv(., "effector_data_info_fungi.csv")
```

## Oomycetes

```{r}
effector_data_info_oomycete <- effector_data_info %>% 
  dplyr::filter(class == "oomycete") 
```


```{r}
effector_data_info_oomycete <- effector_data_info_oomycete %>% 
  group_by(Pathogenspecies) %>% 
  summarise(count = n())

effector_data_info_oomycete
```


```{r}
effector_data_info_oomycete %>% 
  data.table::fwrite("../../../data/secreted_data/signalp-pipeline/oomycete_lookup_table.csv")
```

