---
title: "Untitled"
author: "Ruth Kristianingsih"
date: "05/08/2019"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("reports", stringr::str_remove(getwd(), here::here("scripts/r-scripts/")))) })
output:
  md_document:
    variant: markdown_github
---

# Can adding more number of iterations on RandomSearchCV() result on better accuracy? (Based on my hypothesis on the previous results)

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
```

## Read the results 

```{r}
pred_results_old <- data.table::fread("../../../../data/model_scripts/df_result_prediction_old.csv",  drop = 'V1')
pred_results_new <- data.table::fread("../../../../data/model_scripts/df_result_prediction_100_combination.csv",  drop = 'V1')
```


Load the all of the results of hyperparameter scan and show the best 30 models. 

```{r}
# Read the CSV files
result_hyper_scan_new <- data.table::fread("../../../../data/model_scripts/result_hyper_tuned.csv", drop = 'V1') %>% 
  dplyr::select(starts_with("param_"), mean_test_score, mean_train_score)

result_hyper_scan_old <- data.table::fread("../../../../data/model_scripts/result_hyper_tuned_old.csv", drop = 'V1') %>% 
  dplyr::select(starts_with("param_"), mean_test_score, mean_train_score)

result_all <- result_hyper_scan_new  %>% 
  rbind(result_hyper_scan_old)

results_hyper_scan_250iters <- result_hyper_scan_new %>% 
   mutate(
  param_num_hidden_layers = str_remove_all(param_num_hidden_layers, "\\["),
  param_num_hidden_layers = str_remove_all(param_num_hidden_layers, "\\]")
  ) %>% 
  separate(param_num_hidden_layers, c("Layer1","Layer2", "Layer3"), sep = "([,])") %>% 
  dplyr::select(-param_shuffle) %>% 
  rename(optimizers = param_optim_methods,
         l2_rate = param_l2_rate, 
         input_hidden_units = param_input_num_hidden_units, 
         input_drop_out = param_input_dropout_rates, 
         epochs = param_epochs, 
         dropout = param_dropout_rates, 
         batch_size = param_batch_size, 
         batch_norm = param_batch_norm, 
         activation = param_activation_function) %>% 
  mutate_all(function(x) ifelse(is.na(x), 0, x)) %>% 
  mutate(
    hidden_layers = (Layer1 != 0) + (Layer2 != 0) + (Layer3 != 0)
  )

results_hyper_scan_100iters <- result_hyper_scan_old %>% 
   mutate(
  param_num_hidden_layers = str_remove_all(param_num_hidden_layers, "\\["),
  param_num_hidden_layers = str_remove_all(param_num_hidden_layers, "\\]")
  ) %>% 
  separate(param_num_hidden_layers, c("Layer1","Layer2", "Layer3"), sep = "([,])") %>% 
  dplyr::select(-param_shuffle) %>% 
  rename(optimizers = param_optim_methods,
         l2_rate = param_l2_rate, 
         input_hidden_units = param_input_num_hidden_units, 
         input_drop_out = param_input_dropout_rates, 
         epochs = param_epochs, 
         dropout = param_dropout_rates, 
         batch_size = param_batch_size, 
         batch_norm = param_batch_norm, 
         activation = param_activation_function) %>% 
  mutate_all(function(x) ifelse(is.na(x), 0, x)) %>% 
  mutate(
    hidden_layers = (Layer1 != 0) + (Layer2 != 0) + (Layer3 != 0)
  )

```


## Random forest
```{r}
#import the package
library(randomForest)
```

```{r}
results_hyper_scan_250iters <- results_hyper_scan_250iters %>% 
  select(-mean_train_score, -batch_norm)

results_hyper_scan_100iters <- results_hyper_scan_100iters %>% 
  select(-mean_train_score, -batch_norm)

# Select all of the column names of hyperparameters in the dataframe
cols <- results_hyper_scan_250iters %>% 
  dplyr::select(-c(mean_test_score)) %>% 
  colnames() 

cols_100 <- results_hyper_scan_100iters %>% 
  dplyr::select(-c(mean_test_score)) %>% 
  colnames() 

# Change all of the hyperparameters variables as factors
results_hyper_scan_250iters[cols] <- lapply(results_hyper_scan_250iters[cols], factor)  

results_hyper_scan_100iters[cols] <- lapply(results_hyper_scan_100iters[cols], factor)  

test_100 <- randomForest(mean_test_score ~ .,
                            data = results_hyper_scan_100iters, 
                            ntree = 100, 
                            mtry = 2, 
                            importance=TRUE)

test_100$rsq[100]*100
```


```{r}
mtry_list <- c(2:10)

num_iter <- length(mtry_list)
var_explained_100 <- numeric(length = num_iter)
var_explained_250 <- numeric(length = num_iter)

for (i in 1:num_iter) {
  rf_classifier <- randomForest(
    mean_test_score  ~ .,
    data = results_hyper_scan_100iters,
    ntree = 1000,
    mtry = mtry_list[i],
    importance = TRUE
  )
  var_explained_100[i] <- rf_classifier$rsq[1000] * 100
}

for (i in 1:num_iter) {
  rf_classifier <- randomForest(
    mean_test_score  ~ .,
    data = results_hyper_scan_250iters,
    ntree = 1000,
    mtry = mtry_list[i],
    importance = TRUE
  )
  var_explained_250[i] <- rf_classifier$rsq[1000] * 100
}
```

```{r}
df_100 <- data.frame(mtry_list, var_explained_100)
df_250 <- data.frame(mtry_list, var_explained_250)

df_100 %>% 
  knitr::kable()
```

```{r}
gg <- ggplot(df_100) +
  aes(x = mtry_list, y = var_explained_100) +
  geom_point()


gg
```

```{r}
rf_classifier <- randomForest(
   mean_test_score  ~ .,
    data = results_hyper_scan_100iters,
    ntree = 1000,
    mtry = df_100[which.max(df_100$var_explained), "mtry_list"],
    importance = TRUE
  )

```

```{r}
rf_classifier_250 <- randomForest(
   mean_test_score  ~ .,
    data = results_hyper_scan_250iters,
    ntree = 1000,
    mtry = df_250[which.max(df_250$var_explained), "mtry_list"],
    importance = TRUE
  )

```




```{r}
rf_classifier
```
Since the best is when mtry = 9, then we will take that. 

```{r}
varImpPlot(rf_classifier)
```


```{r}
varImpPlot(rf_classifier_250)
```


```r
mean_test <- result_hyper_scan %>% 
  select(mean_test_score) 

mean_test %>% 
  arrange(desc(mean_test$mean_test_score))
```



```{r}
library(ggplot2)
library(tidyverse)

# results_all <- readRDS("../../scripts/model-scripts/Rmd/results_all.RDS")

plot_single_variable <- function(data, variable, filter_size, y_low_lim = 0.41, y_upp_lim = 0.75) {
  if(!is.null(filter_size)) {
    data <- data %>% 
      dplyr::filter(filters == filter_size)
  }
  
  plot <- ggplot(data) +
    aes(x = {{ variable }}, y = mean_test_score) +
    geom_point() +
    scale_y_continuous(limits = c(y_low_lim, y_upp_lim)) +
    labs(
      y = "Mean accuracy"
    )
  
  return(plot)
}


plot_all_variables <- function(data, filter_size = NULL) {
  plot_matrix <- GGally::ggmatrix(
    list(
      plot_single_variable(data, optimizers, filter_size),
      plot_single_variable(data, Layer1, filter_size),
      plot_single_variable(data, Layer2, filter_size),
      plot_single_variable(data, Layer3, filter_size),
      plot_single_variable(data, l2_rate, filter_size),
      plot_single_variable(data, input_hidden_units, filter_size),
      plot_single_variable(data, input_drop_out, filter_size), 
      plot_single_variable(data, epochs, filter_size),
      plot_single_variable(data, dropout, filter_size),
      plot_single_variable(data, batch_size, filter_size),
      # plot_single_variable(data, batch_norm, filter_size),
      plot_single_variable(data, activation, filter_size),
      plot_single_variable(data, hidden_layers, filter_size)
    ),
    nrow = 1, ncol = 13,
    xAxisLabels = c("optimizers", 
                    "Layer1", 
                    "Layer2", 
                    "Layer3", 
                    "l2_rate",           
                    "input_hidden_units",
                    "input_drop_out",  
                    "epochs",   
                    "dropout",           
                    "batch_size",     
                    # "batch_norm",    
                    "activation",       
                    "hidden_layers"),
    ylab = "Mean Acc"
  ) +
    theme(strip.placement = "outside")

  return(plot_matrix)
}

gg_best_hyper_values <- plot_all_variables(results_hyper_scan_250iters)

gg_best_hyper_values
```

```{r}
cols
```

```{r}
# Read the CSV of the prediction results on the test data
predict_results <- data.table::fread("../../../../data/model_scripts/df_result_prediction_100_combination.csv", drop = "V1")

# Show the results by sort the accuracy
predict_results %>% 
  arrange(Accuracy) %>%  
  knitr::kable()
```
